- name: caddy-install
  hosts: all
  become: true
  roles:
    - role: caddy_ansible.caddy_ansible
      caddy_systemd_capabilities_enabled: true
      caddy_packages: [
        "github.com/caddy-dns/cloudflare"
      ]
      caddy_config: |
        http://localhost:80
        respond "Hello, world!"
  tasks:
    - name: Allow connections on multiple ports
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - 22 # Teleport
          - 2222 # ssh
          - 80
          - 443 # http/https
          - 6443 # kubernetes
        jump: ACCEPT
        flush: yes
